[package]
name = "scylla-tools-01"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
aya = { git = "https://github.com/aya-rs/aya", branch="main" }
scylla-tools-01-common = { path = "../scylla-tools-01-common", features=["user"] }
anyhow = "1.0.42"
ctrlc = "3.2"

structopt = { version = "0.3"}

[[bin]]
name = "scylla-tools-01"
path = "src/main.rs"
